export const USER = "USER";
export const ADMIN_PANEL_CONSTANTS = "ADMIN_PANEL_CONSTANTS";
export const RESTAURANTS_DATA = "RESTAURANTS_DATA";
export const ORDERS_DATA = "ORDERS_DATA";
export const SELECTED_RESTAURANT = "SELECTED_RESTAURANT";
export const CUSTOMERS_DATA = "CUSTOMERS_DATA";
